#!/usr/bin/env python3
"""Render the rubric baseline table from the corpus.

    python tests/errors/report.py                 # markdown to stdout
    python tests/errors/report.py --write         # overwrite docs/.../BASELINE.md

Reads only ``case.json`` files, so it never runs PDL and is instant. Re-run and
commit the delta after any Phase-3 change: the movement is the deliverable.
"""

from __future__ import annotations

import re
import sys
from collections import defaultdict
from pathlib import Path

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
    from tests.errors.harness import RUBRIC_DIMENSIONS, Case, load_cases
else:  # pragma: no cover
    from .harness import RUBRIC_DIMENSIONS, Case, load_cases

BASELINE_PATH = (
    Path(__file__).resolve().parents[2] / "docs" / "error-reporting" / "BASELINE.md"
)
INVENTORY_PATH = BASELINE_PATH.with_name("INVENTORY.md")
MAX_PER_DIMENSION = 3

_TAXONOMY_ID = re.compile(r"\bE-[A-Z]+-\d{3}\b")


def taxonomy_ids() -> set[str]:
    """Every error ID named in the taxonomy, whether or not it has a reproducer.

    The corpus is a *subset* of the taxonomy: some classes have no reproducer
    yet, and a few cannot have one from the CLI at all. Deriving the count here
    rather than stating it keeps the coverage gap from being quietly overstated
    -- this summary previously claimed one entry per reproducible class, which
    was 21 entries short of true.
    """
    if not INVENTORY_PATH.exists():  # pragma: no cover - the doc is committed
        return set()
    return set(_TAXONOMY_ID.findall(INVENTORY_PATH.read_text(encoding="utf-8")))


def _bar(total: int) -> str:
    filled = round(total / (MAX_PER_DIMENSION * len(RUBRIC_DIMENSIONS)) * 10)
    return "█" * filled + "░" * (10 - filled)


def _flags(case: Case) -> str:
    marks = []
    if case.rubric.get("hygiene_traceback_expected"):
        marks.append("TB")
    if case.rubric.get("hygiene_unstable_order"):
        marks.append("ORD")
    if case.rubric.get("hygiene_silent_failure"):
        marks.append("SIL")
    return " ".join(marks)


def render(cases: list[Case]) -> str:
    out: list[str] = []
    w = out.append

    w("# PDL Diagnostic Baseline")
    w("")
    w(
        "Rubric scores for every corpus entry, as of the commit this file was "
        "last regenerated in. Generated by `python tests/errors/report.py "
        "--write`; do not edit by hand."
    )
    w("")
    w(
        "Scale and conventions are in [`RUBRIC.md`](RUBRIC.md). "
        "`TB` marks an entry that leaks a Python traceback; `ORD` marks one whose "
        "message order varies with the hash seed; `SIL` marks one that fails "
        "silently."
    )
    w("")

    total_possible = MAX_PER_DIMENSION * len(RUBRIC_DIMENSIONS) * len(cases)
    total_actual = sum(c.rubric_total for c in cases)
    tb = sum(1 for c in cases if c.rubric.get("hygiene_traceback_expected"))
    silent = sum(1 for c in cases if c.rubric.get("hygiene_silent_failure"))

    w("## Summary")
    w("")
    taxonomy = taxonomy_ids()
    uncovered = sorted(taxonomy - {c.id for c in cases})
    if taxonomy:
        # Entries and IDs are not the same count. One taxonomy ID can need more
        # than one reproducer -- `E-SCHEMA-006` needs a second for the fallback
        # branch its first reproducer stopped reaching -- and printing the entry
        # count as the coverage figure overstates coverage by exactly that many.
        covered = len(taxonomy & {c.id for c in cases})
        w(
            f"- **{len(cases)} corpus entries**, covering {covered} of the "
            f"**{len(taxonomy)}** error IDs in the taxonomy."
        )
    else:  # pragma: no cover - the doc is committed
        w(f"- **{len(cases)} corpus entries**.")
    w(
        f"- **{total_actual} / {total_possible}** rubric points "
        f"(**{100 * total_actual / total_possible:.0f}%**)."
    )
    w(
        f"- **{tb} {'entry leaks' if tb == 1 else 'entries leak'} a Python "
        "traceback** to the user."
    )
    w(
        f"- **{silent} {'entry fails' if silent == 1 else 'entries fail'} "
        "silently** — a broken program that exits 0 and reports nothing at all."
    )
    w("")

    if uncovered:
        w(
            f"**{len(uncovered)} taxonomy IDs have no reproducer**, so every "
            "score below is a score of the covered subset and not of PDL's "
            "diagnostics as a whole:"
        )
        w("")
        w("> " + ", ".join(f"`{i}`" for i in uncovered))
        w("")

    w("## Per-dimension totals")
    w("")
    w("| Dimension | Score | of | Mean |")
    w("| --- | ---: | ---: | ---: |")
    for dim in RUBRIC_DIMENSIONS:
        got = sum(c.rubric.get(dim, 0) for c in cases)
        cap = MAX_PER_DIMENSION * len(cases)
        w(f"| {dim.capitalize()} | {got} | {cap} | {got / len(cases):.2f} |")
    w("")

    w("## By error class")
    w("")
    w("| Class | Entries | Score | of | Mean / 15 |")
    w("| --- | ---: | ---: | ---: | ---: |")
    by_class: dict[str, list[Case]] = defaultdict(list)
    for case in cases:
        by_class["-".join(case.id.split("-")[:2])].append(case)
    for cls in sorted(by_class):
        group = by_class[cls]
        got = sum(c.rubric_total for c in group)
        cap = MAX_PER_DIMENSION * len(RUBRIC_DIMENSIONS) * len(group)
        w(f"| {cls} | {len(group)} | {got} | {cap} | {got / len(group):.1f} |")
    w("")

    w("## Every entry, worst first")
    w("")
    header = " | ".join(d[:3].upper() for d in RUBRIC_DIMENSIONS)
    w(f"| ID | Sev | {header} | Total | | Flags | Title |")
    w(
        "| --- | --- | "
        + " | ".join(["---:"] * len(RUBRIC_DIMENSIONS))
        + " | ---: | --- | --- | --- |"
    )
    for case in sorted(cases, key=lambda c: (c.rubric_total, c.id)):
        scores = " | ".join(str(case.rubric.get(d, 0)) for d in RUBRIC_DIMENSIONS)
        w(
            f"| `{case.id}` | {case.severity} | {scores} | "
            f"**{case.rubric_total}** | `{_bar(case.rubric_total)}` | "
            f"{_flags(case)} | {case.title} |"
        )
    w("")

    w("## Notes per entry")
    w("")
    for case in sorted(cases, key=lambda c: c.id):
        w(f"**`{case.id}`** — {case.title}  ")
        w(f"{case.notes}")
        w("")

    return "\n".join(out)


def main(argv: list[str]) -> int:
    cases = load_cases()
    if not cases:
        print("no corpus entries found", file=sys.stderr)
        return 1
    text = render(cases)
    if "--write" in argv:
        BASELINE_PATH.write_text(text, encoding="utf-8")
        print(f"wrote {BASELINE_PATH.relative_to(Path.cwd())}")
    else:
        print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
