#!/usr/bin/env python3
"""Render the rubric baseline table from the corpus.

    python tests/errors/report.py                 # markdown to stdout
    python tests/errors/report.py --write         # overwrite docs/.../BASELINE.md

Reads only ``case.json`` files, so it never runs PDL and is instant. Re-run and
commit the delta after any Phase-3 change: the movement is the deliverable.
"""

from __future__ import annotations

import sys
from collections import defaultdict
from pathlib import Path

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
    from tests.errors.harness import RUBRIC_DIMENSIONS, Case, load_cases
else:  # pragma: no cover
    from .harness import RUBRIC_DIMENSIONS, Case, load_cases

BASELINE_PATH = (
    Path(__file__).resolve().parents[2] / "docs" / "error-reporting" / "BASELINE.md"
)
MAX_PER_DIMENSION = 3


def _bar(total: int) -> str:
    filled = round(total / (MAX_PER_DIMENSION * len(RUBRIC_DIMENSIONS)) * 10)
    return "█" * filled + "░" * (10 - filled)


def _flags(case: Case) -> str:
    marks = []
    if case.rubric.get("hygiene_traceback_expected"):
        marks.append("TB")
    if case.rubric.get("hygiene_unstable_order"):
        marks.append("ORD")
    return " ".join(marks)


def render(cases: list[Case]) -> str:
    out: list[str] = []
    w = out.append

    w("# PDL Diagnostic Baseline")
    w("")
    w(
        "Rubric scores for every corpus entry as of the Phase-1 baseline commit. "
        "Generated by `python tests/errors/report.py --write`; do not edit by hand."
    )
    w("")
    w(
        "Scale and conventions are in [`RUBRIC.md`](RUBRIC.md). "
        "`TB` marks an entry that leaks a Python traceback; `ORD` marks one whose "
        "message order varies with the hash seed."
    )
    w("")

    total_possible = MAX_PER_DIMENSION * len(RUBRIC_DIMENSIONS) * len(cases)
    total_actual = sum(c.rubric_total for c in cases)
    tb = sum(1 for c in cases if c.rubric.get("hygiene_traceback_expected"))
    silent = sum(1 for c in cases if c.expect_exit == 0 and c.severity == "S0")

    w("## Summary")
    w("")
    w(f"- **{len(cases)} corpus entries**, one per reproducible taxonomy class.")
    w(
        f"- **{total_actual} / {total_possible}** rubric points "
        f"(**{100 * total_actual / total_possible:.0f}%**)."
    )
    w(f"- **{tb} entries leak a Python traceback** to the user.")
    w(
        f"- **{silent} entries fail silently** — a broken program that exits 0 "
        "with no diagnostic at all."
    )
    w("")

    w("## Per-dimension totals")
    w("")
    w("| Dimension | Score | of | Mean |")
    w("| --- | ---: | ---: | ---: |")
    for dim in RUBRIC_DIMENSIONS:
        got = sum(c.rubric.get(dim, 0) for c in cases)
        cap = MAX_PER_DIMENSION * len(cases)
        w(f"| {dim.capitalize()} | {got} | {cap} | {got / len(cases):.2f} |")
    w("")

    w("## By error class")
    w("")
    w("| Class | Entries | Score | of | Mean / 15 |")
    w("| --- | ---: | ---: | ---: | ---: |")
    by_class: dict[str, list[Case]] = defaultdict(list)
    for case in cases:
        by_class["-".join(case.id.split("-")[:2])].append(case)
    for cls in sorted(by_class):
        group = by_class[cls]
        got = sum(c.rubric_total for c in group)
        cap = MAX_PER_DIMENSION * len(RUBRIC_DIMENSIONS) * len(group)
        w(f"| {cls} | {len(group)} | {got} | {cap} | {got / len(group):.1f} |")
    w("")

    w("## Every entry, worst first")
    w("")
    header = " | ".join(d[:3].upper() for d in RUBRIC_DIMENSIONS)
    w(f"| ID | Sev | {header} | Total | | Flags | Title |")
    w(
        "| --- | --- | "
        + " | ".join(["---:"] * len(RUBRIC_DIMENSIONS))
        + " | ---: | --- | --- | --- |"
    )
    for case in sorted(cases, key=lambda c: (c.rubric_total, c.id)):
        scores = " | ".join(str(case.rubric.get(d, 0)) for d in RUBRIC_DIMENSIONS)
        w(
            f"| `{case.id}` | {case.severity} | {scores} | "
            f"**{case.rubric_total}** | `{_bar(case.rubric_total)}` | "
            f"{_flags(case)} | {case.title} |"
        )
    w("")

    w("## Notes per entry")
    w("")
    for case in sorted(cases, key=lambda c: c.id):
        w(f"**`{case.id}`** — {case.title}  ")
        w(f"{case.notes}")
        w("")

    return "\n".join(out)


def main(argv: list[str]) -> int:
    cases = load_cases()
    if not cases:
        print("no corpus entries found", file=sys.stderr)
        return 1
    text = render(cases)
    if "--write" in argv:
        BASELINE_PATH.write_text(text, encoding="utf-8")
        print(f"wrote {BASELINE_PATH.relative_to(Path.cwd())}")
    else:
        print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
